### ISSUE TITLE
Bug in higher-order matching

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/lambdapi#225]
I am sorry, I don't have time to minimize the example. I am aware of a type checking issue in Lambdapi which is probably related to Higher-Order matching. The error can be found in the Librairies repository. There are two files in play. The first one encodes Cedille's core theory: [cedille.dk](https://github.com/Deducteam/Libraries/blob/master/theories/cedille.dk) . The second one encodes a basic example with it: [nat.dk](https://github.com/Deducteam/Libraries/blob/master/examples/cedille/nat.dk).

The first file type checks but not the second in Lambdapi (but it does in Dedukti and Dedukti is right on this one). I know that the error commes from either [this rule](https://github.com/Deducteam/Libraries/blob/024cb976dbb55f05e69a5e9c5ccca95e1ecee15d/theories/cedille.dk#L93) or [this rule](https://github.com/Deducteam/Libraries/blob/024cb976dbb55f05e69a5e9c5ccca95e1ecee15d/theories/cedille.dk#L99) which are both Higher-Order rules. One of these rules is not applied while it should.

**Comment by gabrielhdt** [comment]
The issue might come from the matching of an abstraction against an applied pattern variable.  The current lambdapi rejects it as line 176 of [eval.ml](https://github.com/Deducteam/lambdapi/blob/master/src/eval.ml) suggests.

**Comment by GuillaumeGen** [comment]
This issue suggests that even in the old syntax, LambdaPi performs syntactic matching rather than matching modulo beta.

**Comment by francoisthire** [comment]
Does your PR @gabrielhdt fixes this issue?

**Comment by gabrielhdt** [comment]
Hum for now it fails to build a tree, precisely because of this case. It should be easy to fix though.

**Comment by gabrielhdt** [comment]
The decision trees branch now behave like the master branch, that is, it raises
```
[cedille.dk, 46:0-51] Term [mk_iota cnat cz inat iz I] does not have type [Term star nat].
```

**Comment by francoisthire** [comment]
Alright, but the file is well-typed, so there is still a bug.

**Comment by GuillaumeGen** [comment]
The error message is weird, since the line which raises the problem is the line 46 of `nat.dk`, not of `cedille.dk`.
The "file is well-typed" depends on the definition of matching. I think refusing this file could have been a reasonable choice, but both implementations must agree.

**Comment by francoisthire** [comment]
@GuillaumeGen Can you detail your comment? Why do you think it depends on the definition of "matching"?

**Comment by rlepigre** [comment]
I can try to have a look later, but you should definitely try to make the example more minimal (just inline `nat.dk` at the end of `cedille.dk`), and also convert it to Lambdapi syntax. The legacy syntax may not be translated accurately, and it would be easier to debug this way.

**Comment by GuillaumeGen** [comment]
As far as I understand, LambdaPi implements AFSM (or something close to it). Hence there are two kind of application, the usual one `x y` and the metavariable one `X[y]`.
The metavariable one comes with arity constraint and in the lhs of a rule you have the pattern restriction (only distinct bound variables). Matching is performed syntactically on usual application and "modulo beta" on meta-variable application.
I put "modulo beta" between quotes since the metavariables have a fixed arity, so it does not really create lambdas.

**Comment by francoisthire** [comment]
Maybe I should mention also that this example comes from the encoding of a type system called `Cedille` from Aaron Stump. It features mainly:
- Dependent intersection types
- Curry style type theory
- Untyped equality

The original file I have provided in this issue aims to encode this logic. Nat is an example that this encoding seems to work. The main benefit of `Cedille` is to be able to derive inductive types. This is the theorem I proved in `Nat.dk`.

From my understanding, PML is not that far from `Cedille`. Maybe it is possible to have an encoding of PML in Dedukti then.

**Comment by fblanqui** [comment]
Remark: the file is checked if we replace the first rule defining code by
```
rule code _ (prod &s1 &s2 &A &B) &f
   → lam (λ (x : pure), code &s2 (&B (uncode &s1 &A x)) (&f (uncode &s1 &A x)))
```

**Comment by fblanqui** [comment]
No.

**Comment by fblanqui** [comment]
And this rule is more general since it applies even if the argument is not a lambda.

**Comment by francoisthire** [comment]
In Cedille it does ^^ .

**Comment by fblanqui** [comment]
How?

**Comment by francoisthire** [comment]
Because using this rule, you maybe have two terms f and \x. f~x which are not equal in Cedille, but their encoding will be because if the encoding of `f` will match the left pattern, and hence, the encoding of both terms will be convertible.

**Comment by fblanqui** [comment]
The "normal form" computed by LP for `code star cnat cz` is:
```
lam (λx,
       code
         star
         (prod
           star
           star
           (prod
             star
             star
             (uncode box ustar dummy)
             (λ__, uncode box ustar dummy))
           (λ__, uncode box ustar dummy))
         (λs, uncode star (uncode box ustar dummy) x))
```
This is not a normal form. It seems that `(λs, uncode star (uncode box ustar dummy) x)` does not match `λs,&f[s]`. I propose the following explanation: `λs, uncode star (uncode box ustar dummy) x` is not recognized as a closed term since it contains the free variable `x`. What do you think @rlepigre ?

**Comment by fblanqui** [comment]
This is indeed the case as shown by the following example:
```
symbol T:TYPE
symbol a:T
symbol f:(T⇒T)⇒T
rule f (λx,&F[x]) → a
compute λx,f(λy,x) // does not return a !
```

**Comment by rlepigre** [comment]
@fblanqui you are right about that, your explanation is correct. The environment `[s]` in `&f[s]` says that the only variable that can appear in a matching term is `s`.

**Comment by fblanqui** [comment]
Will it be easy to fix? It seems that we cannot use is_closed. Instead we need to check that some variables do not occur. Is it possible to do this efficiently with Bindlib?

**Comment by rlepigre** [comment]
But is that really a bug though? For me this looks like some variable is gonna escape its scope here.

**Comment by francoisthire** [comment]
If you have a rule 
```lambdapi
rule foo &x &y --> &x
```
it matches the term `foo z z`. The fact that `z` is free is not a problem right? You don't expect that the term that matches the variable `&x` is closed.

When you encounter the rule
```lambdapi
rule foo (\x. &f[x]) --> f[0].
```

You cannot assume, for the same reason that any term which matches `f[x]` has only `x` has as a free variable. At least, this is not what it is intended when Miller's presented its restriction. And the current behavior implemented by Dedukti is the one implemented by every other languages supporting the Miller's pattern fragment I know.

**Comment by gabrielhdt** [comment]
I have a branch with dtrees that solves Frederic subproblem, but not Francois'

**Comment by fblanqui** [comment]
@rlepigre , this is the difference between programming languages and proof assistants: in proof assistants, we want to compute strong normal forms, hence reduce under lambda's.

**Comment by fblanqui** [comment]
@gabrielhdt , thanks to give a link to your branch.

**Comment by gabrielhdt** [comment]
https://github.com/gabrielhdt/lambdapi/tree/hobug

**Comment by rlepigre** [comment]
Sorry guys, I really don't have time to have a closer look right now, but I'll try to do that during the weekend or early next week. I had a quick look at your branch @gabrielhdt, and I think that what you do cannot work: free variables may appear in terms through reduction with that approach. (Remember that whenever a binder is destructed, e.g., with `unbind`, it must be reconstructed with `bind_var`.) It is actually important that the constructed binders are closed during matching, to ensure that no variable escape. A solution to the problem will likely involve carrying around yet another environment. But I'm not sure I understand what variables it should contain.

**Comment by fblanqui** [comment]
We must remember the unbind'ed variables. Take
```
symbol T:TYPE
symbol a:T
symbol f:(T⇒T⇒T)⇒T
rule f (λx,λy,&F[x]) → a
```
When matching &F[x] against t, we must check that y does not occur in t.

**Comment by Gaspi** [comment]
One more unexpected behavior (in old syntax):
```
N : Type.
0 : N.

def f : N -> N.
[x] f x --> 0.

def g : (N -> N) -> N.
[h] g (x => h x) --> 0.

#EVAL[SNF] ( y => g (x => 0  ) ).   (;  λy, 0               ;)
#EVAL[SNF] ( y => g (x => x  ) ).   (;  λy, 0               ;)
#EVAL[SNF] ( y => g (x => y  ) ).   (;  λy, g (λx, y)       ;)
#EVAL[SNF] ( y => g (x => f y) ).   (;  λy, g (λx, 0)   !!! ;)
```
The first two SNF are correct, the third is the problem mentioned by @fblanqui .
The last SNF command returns the first example which is not a normal form.

**Comment by fblanqui** [comment]
@gabrielhdt , your branch does seem to work, does it? The following file 225.lp (that you should use instead of ho_bug.lp) fails:
```
symbol T:TYPE
symbol a : T
symbol f : (T⇒T)⇒T
rule f (λx,&F[x]) → a
assert f (λx,x) ≡ a
```
Various other files in tests/OK fail too:
```
KO tests/OK/abstractions.lp
[tests/OK/abstractions.lp, 12:0-47] Assertion failed.
KO tests/OK/freevars-constraints.lp
[tests/OK/freevars-constraints.lp, 12:0-57] Assertion failed.
KO tests/OK/ho_bug2.dk
[tests/OK/ho_bug2.dk, 12:0-27] Assertion failed.
KO tests/OK/miller2.dk
[tests/OK/miller2.dk, 51:0-40] Assertion failed.
```

**Comment by gabrielhdt** [comment]
Ah indeed various test files are not ok.  The file you provided earlier was and is ok.

**Comment by fblanqui** [comment]
Yes, but it was just a compute, not an assert.

**Comment by gabrielhdt** [comment]
I visually checked the result to be the comment you wrote beside the compute, that is `\lambda x, a`

**Comment by fblanqui** [comment]
@Gaspi , the 4th case is in fact the same bug. For computing the SNF, LP first computes the WHNF. When an application (t u) is in WHNF, then it computes the SNF of t and u. Here, because g(λx,f y) is in WHNF (wrongly), it computes the SNF of g and λx,f y, which are g and λx,0 respectively.

**Comment by gabrielhdt** [comment]
I have fixed my branch, tests pass and Francois' file passes

**Comment by fblanqui** [comment]
Great! Does it work with https://github.com/Deducteam/lambdapi/issues/225#issuecomment-513223702 too? Why not pushing this to your master?

In eval.ml, you can improve your code by not building forbidden, that is replace:
```
              let forbidden = VarMap.fold (fun _ sv acc ->
                  if Array.mem sv xs then acc else VarSet.add sv acc) to_stamped
                  VarSet.empty in
              let r = VarSet.for_all (fun sv -> not @@ Bindlib.occur sv b)
                  forbidden in
```
by something like:
```
              let exception Fail in
              let r =
                 try
                   VarMap.iter (fun _ sv ->
                      if not (Array.mem sv xs) && Bindlib.occur sv b then raise Fail) to_stamped;
                   true in
                with Fail -> false
```

**Comment by gabrielhdt** [comment]
The file iss225 embeds both example and both work.  There is definitely room for optimisation, and exception seem to be a good solution.  I have merged with my master.

**Comment by fblanqui** [comment]
Will be fixed by merging https://github.com/Deducteam/lambdapi/pull/172.

**Comment by rlepigre** [comment]
Let's not close until the bug has been fixed in master (I'll take care of that now), especially since #172 is not ready to be merged in my opinion. I'll review it right after I fix master.

**Comment by fblanqui** [comment]
Could you please explain why Gabriel's branch does not solve the problem? Do you have an example?

**Comment by rlepigre** [comment]
In fact I'm not sure, I'm still trying to understand what is happening. There are several issues going on at the same time. Solving the issue naively may lead to free variables escaping their scope if we are not careful. For instance, consider the following example.
```
symbol const T : TYPE
symbol const e : T

symbol get : (T ⇒ T) ⇒ T
rule get (λx, &f) → &f

// Should give [e]
compute get (λx, (λ _, e) x)
```
What used to happen here was that `&f` was set to be `(λ _, e) x`, which was obviously wrong since `x` escaped its scope, even though the result was still correct in the end (`x` eventually disappears through computation).

With the approach that I am considering now, this issue is solved. However, I now run into the problem that `(λ _, e) x` cannot match `&f` unless we first evaluate it to `e`. In general, we may need an arbitrary number of reduction steps, at arbitrary places, to ensure that "forbidden" variables disappear (and weak head normalization is not enough). I'm not sure what is the desired approach here. One solution would be to compute the (strong) normal form before matching, which would guarantee that every variable that can disappear does disappear. But that that's probably not "lazy" enough, is it?

Does Dedukti do anything special to enforce that free variables do not escape their scope @francoisthire?
And is anything special done for that kind of case in your branch @gabrielhdt?

**Comment by francoisthire** [comment]
Maybe @barras or @Gaspi will give a better answer than mine. But in Dedukti you canot write your rule. We have a restriction that the arity of every variable on the righ-hand side of the rule should be greater than any occurence of this symbol on the left-hand side.

But [here](https://github.com/Deducteam/Dedukti/blob/b830dcf93e34df825f9c02d4567c08ac02dffdc1/kernel/reduction.ml#L127), I think we try also to solve this problem by computing the snf of the argument if the matching failed beforehand.

**Comment by gabrielhdt** [comment]
In my branch, `&f` would be `(\lambda _ e) x` as you said.  But I don't see why it is wrong.  On the other hand, indeed unless we beta normalise, the term won't match since `&f` must contain no free variable.

**Comment by rlepigre** [comment]
@gabrielhdt it is very wrong because reducing `get (λx, (λ _, e) x)` (which is closed) will produce `(λ _, e) x` (which is open) as an intermediate step. The fact that `x` will here be erased after a step of beta-reduction is a pure coincidence, and if it would be very much possible that a variable escapes through this mechanism.

**Comment by rlepigre** [comment]
@francoisthire my example comes from a simplification of the `ho_bug1.dk` file (see [here](https://github.com/Deducteam/lambdapi/blob/master/tests/OK/ho_bug1.dk)) that is used in our unit tests. The problem with this example (under my attempted fix) is essentially the same, so I don't understand why Dedukti would reject the above example and still allow the example in `ho_bug1.dk`.

**Comment by fblanqui** [comment]
Rodolphe, I believe that there is a misunderstanding about what Gabriel said. Gabriel, correct me if I am wrong but I think that you said that, currently, in your branch, `get (λx, (λ _, e) x)` does not reduce because `(λ _, e) x` contains `x`. If we were reducing `(λ _, e) x` before testing variables, we would get `e` and then, indeed, `get (λx, (λ _, e) x)` would be reducible to `e` because `e` does not contain `x`. So, you are right Rodolphe, this reduction strategy is not complete. But free variables are preserved: no bound variable will escape its scope. To fix this new problem (strategy completeness), we need to strongly normalize the argument before testing variables. Note however that this is necessary only when there are forbidden variables indeed, and this is very rare in practice. So, Gabriel, I am thinking that, in your decision trees, you should have a variable test only if there are forbidden variables like in Rodolphe's example. For instance, in `f (λx,g(F[x])) → r`, there is no check to do. Is it what you implemented?

**Comment by gabrielhdt** [comment]
That is indeed what I meant.  However, this is what I thought I implemented, and in fact, I just found a bug in some auxiliary function.  I'm fixing this.

Regarding the conditional test, I intended to do this, but some tests failed, namely the `miller` ones, because I had to check that variables are swapped in [this test](https://github.com/gabrielhdt/lambdapi/blob/fe2084d2ddd98770770964b0a03b12712e50cb56/tests/OK/abstractions.lp#L12).  Otherwise, decision on whether a test has to be done is done at compile time and takes into account the bracketed variables and the traversed lambda; it is done [here](https://github.com/gabrielhdt/lambdapi/blob/fe2084d2ddd98770770964b0a03b12712e50cb56/src/dtree.ml#L460).

**Comment by gabrielhdt** [comment]
So as of commit 4e458b7ec224b3574bda8e7d6fb59d4bbd8b5a2e, the expected behaviour announced by Frederic operates.

Additionally, I've made clearer what I stated above, see [here](https://github.com/gabrielhdt/lambdapi/blob/4e458b7ec224b3574bda8e7d6fb59d4bbd8b5a2e/src/dtree.ml#L403) and [there](https://github.com/gabrielhdt/lambdapi/blob/4e458b7ec224b3574bda8e7d6fb59d4bbd8b5a2e/src/dtree.ml#L477).  In both lines, one condition translates "check for free variables if some are forbidden", the other part forces the variable check in case of permutation of free variables as shown [there](https://github.com/gabrielhdt/lambdapi/blob/fe2084d2ddd98770770964b0a03b12712e50cb56/tests/OK/abstractions.lp#L12).

**Comment by rlepigre** [comment]
@gabrielhdt How about efficiency in your branch? Have you tested `make matita` and the likes?

**Comment by francoisthire** [comment]
> @francoisthire my example comes from a simplification of the ho_bug1.dk file (see here) that is used in our unit tests. The problem with this example (under my attempted fix) is essentially the same, so I don't understand why Dedukti would reject the above example and still allow the example in ho_bug1.dk.

I made a mistake in my answer. I thought that `f` was applied to `x` in the pattern. Since it is not the case, you need to take into account the second part of my answer, not the first part.

**Comment by gabrielhdt** [comment]
@rlepigre on verine, performance does not change

**Comment by rlepigre** [comment]
@gabrielhdt OK, no worries. I started to give comments on your PR, but I'll do that in several waves. It would be nice to merge it soon, and solve the problems at the same time. I don't want to spend time optimizing the version I fixed, it is probably better to finish the work on decision trees.

**Comment by francoisthire** [comment]
Is it possible to get a behavior similar to the current one once @gabrielhdt PR will be merged?

**Comment by gabrielhdt** [comment]
wdym?

**Comment by fblanqui** [comment]
@gabrielhdt I don't understand why you have to check variable occurrences when there is a permutation. In abstractions.lp there should be no test on variables.

**Comment by gabrielhdt** [comment]
@fblanqui in fact it is a trivial variable check, but I need to remap the right variables into the term, and this is done by a variable check.

**Comment by fblanqui** [comment]
I don't understand. If you take `f (λx, λy, &F[x,y]) → r`, there is nothing to do whatever `r` is. Idem for `f (λx, λy, &F[y,x]) → r`. Assume that you try to match `λx, λy, t` against `λx, λy, &F[x,y]`, then `F` will be set to `λx, λy, t`. If you try to match against `λx, λy, &F[y,x]` then `F` will be set set to `λy, λx, t` because abstractions are done in the order of the arguments of `F`. And all this does not depend on `r`. If `r` contains `F[a,b]` then it will be replaced by `t{x=a,y=b}` in the first case, and `t{x=b,y=a}` in the second case. But this is taken care by the substitution mechanism.

**Comment by gabrielhdt** [comment]
I was mistaken, it has nothing to do with permutation.  However, during evaluation, I unbind terms using variables created at compile time.  In the end, I must gather the free variables introduced and bind them into right hand side.  This is currently done by a variable check, which performs a `lift` to get the variables, and then a `bind_mvar`.  It is possible to do it outside the free variable check though, if you want to separate things.

**Comment by fblanqui** [comment]
Yes, it would be better to separate the two.

**Comment by gabrielhdt** [comment]
Commit 2494410c00874b3321ec8652c78ee2cc3c0d0bfd separates the two, and no free var check is done in `abstractions.lp`.
